dist: xenial
addons:
  apt:
    packages:
    - libxinerama-dev
    - libasound2-dev
    - mesa-common-dev
    - libgl-dev
    - libxi-dev
    - zip

language: node_js
node_js: 10

env:
  - BUILD_TARGET=debug-html5 BUILD_OPTS=""
  - BUILD_TARGET=html5 BUILD_OPTS=""
  - BUILD_TARGET=linux BUILD_OPTS="--compile"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/593f9ec49210b8694911
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

script:
  - git clone --depth=1 --branch update-kha-template https://github.com/haxeui/haxeui-templates.git
  - cd haxeui-templates/kha/skeleton
  - git clone --recursive --single-branch --depth=1 https://github.com/Kode/Kha.git
  - mkdir Libraries
  - cd Libraries
  - git clone --branch $TRAVIS_BRANCH --single-branch --depth=1 https://github.com/haxeui/haxeui-core.git
  - git clone --branch $TRAVIS_BRANCH --single-branch --depth=1 https://github.com/haxeui/haxeui-kha.git
  - git clone --single-branch --depth=1 https://github.com/haxefoundation/hscript.git
  - cd ..
  - node Kha/make $BUILD_TARGET $BUILD_OPTS
